# Generated by Django 5.0.6 on 2024-07-07 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_tlp', '0003_producto_planta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registroproduccion',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registroproduccion',
            name='anulado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anulador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registroproduccion',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
